### PR TITLE
Notebook tweaks for AWS

### PR DESCRIPTION
**Pull request by gmertes**
Just some small tweaks to the notebooks specific to the AWS environment:

* Reduce memory usage for SSL notebook to get it to run with 16GB RAM
* Add the `%matplotlib inline` magic command to get figures to automatically show up
* Ignore warnings. The default environment has some slightly outdated modules that spam deprecations warnings, but work fine otherwise. 
* Change `n_jobs` to -1 (use all available cores)

### CODE REVIEW

**Comment by chanshing** [comment]
Do you guys have acces to this? https://github.blog/changelog/2023-03-01-feature-preview-rich-jupyter-notebook-diffs/

**Comment by gmertes** [comment]
I didn't modify anything to the actual functionality of the notebooks, and also tested all of these on to AWS environment. So it should be ok.

**Review by chanshing — APPROVED** [review]
Looks good to me.

**Comment by chanshing** [comment]
@angerhang @gmertes If you go to Feature Preview and enable "Rich Jupyter Notebooks Diff" you will see the changes like this:
image

**Pull request merged**
